### ISSUE TITLE
Decode throws if payload is IDictionary<string,obj>

### ISSUE THREAD

**Issue by liammclennan** [johnsheehan/jwt#13]
It seems like it should be ok for the payload to be an `IDictionary` but it fails to Deserialize. My work-around for the time being is simply to load my IDictionary back into a Dictionary. 

    IDictionary<string,obj> payload = ...
    JWT.JsonWebToken.Encode(new Dictionary<string,obj>(payload), ...

**Comment by cmatskas** [comment]
@liammclennan are you using the NuGet package or the source code? I'm actually passing an IDictionary and it works fine. Any examples?

**Comment by liammclennan** [comment]
NuGet.

**Comment by cmatskas** [comment]
Are you still facing issues?

**Comment by liammclennan** [comment]
I forget, but I think my work-around for the time being is simply to load my IDictionary back into a Dictionary..

**Comment by cmatskas** [comment]
I can verify that the IDictionary works fine. You may want to get latest and try again :)

**Comment by liammclennan** [comment]
Thanks.

On Fri, May 1, 2015 at 9:03 AM, Christos Matskas <notifications@github.com>
wrote:

> I can verify that the IDictionary works fine. You may want to get latest
> and try again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnsheehan/jwt/issues/13#issuecomment-97995173>.
>



-- 
Liam McLennan.

liam@eclipsewebsolutions.com.au
http://www.eclipsewebsolutions.com.au

**Comment by mikelehen** [comment]
Closing this out.  Holler if you're still having trouble with the latest version.
