### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by MikeChristensen** [johnsheehan/jwt#14]
This assembly is not signed with a key, which makes it impossible to use with assemblies that must be GAC'ed.

**Comment by darrelmiller** [comment]
Microsoft are no longer Strong Naming assemblies in ASP.NET 5.  Their guidance has changed regarding strong naming.
http://stackoverflow.com/questions/28352756/microsoft-aspnet-http-does-not-have-a-strong-name

**Comment by MikeChristensen** [comment]
Oh wow, that I didn't know!  I wonder if that means that you'll be able to
GAC things that aren't signed in v.Next.  Anyway, we were able to work
around the limitation.  We now ilmerge the binaries we need into one
assembly, and then sign that.  Thanks for getting back to me!

**Comment by darrelmiller** [comment]
For ASP.NET Core CLR there is no more GAC, for the full desktop CLR there is a GAC and I recall the signing rules are different, but I don't know the details off hand.

**Comment by mikelehen** [comment]
Thanks for chiming in, @darrelmiller.  I'm closing this out for now.  If anybody's blocked by this, feel free to holler and we can revisit.

**Comment by balajikandasamy** [comment]
I am using an assembly https://github.com/salesforce-marketingcloud/FuelSDK-CSharp that's dependent on JWT. If the assembly is not signed I am not able to deploy the dll to GAC. The FuelSDK is also not signed and the team has agreed to release it out next week. The StackOverflow post mentioned above has been updated and the assemblies are signed in ASP.NET 5 now. Ref: https://github.com/salesforce-marketingcloud/FuelSDK-CSharp/issues/70

**Comment by abatishchev** [comment]
hi, was Jwt.Net ever signed? No, to my knowledge. And I don't see (FuelSDK-CSharpSDK)[https://www.nuget.org/packages/FuelSDK-CSharpSDK] depends on [Jwt.Net](https://www.nuget.org/packages/JWT/).

**Comment by balajikandasamy** [comment]
Please check this one is the nugget package I'm taking about
https://www.nuget.org/packages/SFMC.FuelSDK/

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abatishchev** [comment]
Please submit a PR to sign it and bump the version to 6.0.0-beta1.

**Comment by abatishchev** [comment]
@balajikandasamy ping. Please contribute if you'd like to see this happen.

**Comment by balajikandasamy** [comment]
Sure I will do that this week.
Thanks,
Bala

**Comment by FishDawg** [comment]
The StackOverflow post mentioned above has been updated and the assemblies are signed in ASP.NET 5. I am submitting a pull request to provide a strong name for all assemblies.
