### ISSUE TITLE
Support Asymmetric Signing (especially RS256)

### ISSUE THREAD

**Issue by abatishchev** [johnsheehan/jwt#9]
Hi,
Will you consider to review and merge the changes to support Google flavored Jwt implementation?
If I understand correctly currently the code doesn't support the algorithm Google supports exclusively. At least it didn't work for me. Particularly - [RS256](https://developers.google.com/accounts/docs/OAuth2ServiceAccount).
[System.IdentityModel.Tokens.Jwt](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/) doesn't support it either.

**Comment by abatishchev** [comment]
Did you have a chance to take a look?

**Comment by abatishchev** [comment]
Did you have a chance to take a look?

**Comment by mikelehen** [comment]
Sorry I haven't been responsive.  I'd gladly accept a pull request to support RS256 signatures, but I probably won't be able to implement it myself (at least in the short term).

**Comment by abatishchev** [comment]
Got it, will try to implement in my spare time, will be my next open source thing to do.

**Comment by abatishchev** [comment]
I'm going to start working on this.

Would you mind to accept a refactoring PR first? Just to normalize/polish the code.

**Comment by abatishchev** [comment]
The issue is addressed by https://github.com/johnsheehan/jwt/pull/18
